/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductionPlanRequestDTO,
  ProductionPlanResponseDTO,
} from '../models/index';
import {
    ProductionPlanRequestDTOFromJSON,
    ProductionPlanRequestDTOToJSON,
    ProductionPlanResponseDTOFromJSON,
    ProductionPlanResponseDTOToJSON,
} from '../models/index';

export interface CreateProductionPlanRequest {
    productionPlanRequestDTO: ProductionPlanRequestDTO;
}

export interface DeleteProductionPlanRequest {
    idPlanning: number;
}

export interface GetProductionPlanByIdRequest {
    idPlanning: number;
}

export interface UpdateProductionPlanRequest {
    idPlanning: number;
    productionPlanRequestDTO: ProductionPlanRequestDTO;
}

/**
 * 
 */
export class ProductionPlanControllerApi extends runtime.BaseAPI {

    /**
     */
    async createProductionPlanRaw(requestParameters: CreateProductionPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionPlanResponseDTO>> {
        if (requestParameters['productionPlanRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'productionPlanRequestDTO',
                'Required parameter "productionPlanRequestDTO" was null or undefined when calling createProductionPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/production-plans/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductionPlanRequestDTOToJSON(requestParameters['productionPlanRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionPlanResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async createProductionPlan(requestParameters: CreateProductionPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionPlanResponseDTO> {
        const response = await this.createProductionPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteProductionPlanRaw(requestParameters: DeleteProductionPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['idPlanning'] == null) {
            throw new runtime.RequiredError(
                'idPlanning',
                'Required parameter "idPlanning" was null or undefined when calling deleteProductionPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/production-plans/{idPlanning}`.replace(`{${"idPlanning"}}`, encodeURIComponent(String(requestParameters['idPlanning']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteProductionPlan(requestParameters: DeleteProductionPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteProductionPlanRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getAllProductionPlansRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductionPlanResponseDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/production-plans`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductionPlanResponseDTOFromJSON));
    }

    /**
     */
    async getAllProductionPlans(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductionPlanResponseDTO>> {
        const response = await this.getAllProductionPlansRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getProductionPlanByIdRaw(requestParameters: GetProductionPlanByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionPlanResponseDTO>> {
        if (requestParameters['idPlanning'] == null) {
            throw new runtime.RequiredError(
                'idPlanning',
                'Required parameter "idPlanning" was null or undefined when calling getProductionPlanById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/production-plans/{idPlanning}`.replace(`{${"idPlanning"}}`, encodeURIComponent(String(requestParameters['idPlanning']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionPlanResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getProductionPlanById(requestParameters: GetProductionPlanByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionPlanResponseDTO> {
        const response = await this.getProductionPlanByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateProductionPlanRaw(requestParameters: UpdateProductionPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductionPlanResponseDTO>> {
        if (requestParameters['idPlanning'] == null) {
            throw new runtime.RequiredError(
                'idPlanning',
                'Required parameter "idPlanning" was null or undefined when calling updateProductionPlan().'
            );
        }

        if (requestParameters['productionPlanRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'productionPlanRequestDTO',
                'Required parameter "productionPlanRequestDTO" was null or undefined when calling updateProductionPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/production-plans/{idPlanning}`.replace(`{${"idPlanning"}}`, encodeURIComponent(String(requestParameters['idPlanning']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProductionPlanRequestDTOToJSON(requestParameters['productionPlanRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductionPlanResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateProductionPlan(requestParameters: UpdateProductionPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductionPlanResponseDTO> {
        const response = await this.updateProductionPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
