/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PageWorkshopResponseDTO,
  Pageable,
  WorkshopRequestDTO,
  WorkshopResponseDTO,
} from '../models/index';
import {
    PageWorkshopResponseDTOFromJSON,
    PageWorkshopResponseDTOToJSON,
    PageableFromJSON,
    PageableToJSON,
    WorkshopRequestDTOFromJSON,
    WorkshopRequestDTOToJSON,
    WorkshopResponseDTOFromJSON,
    WorkshopResponseDTOToJSON,
} from '../models/index';

export interface CreateWorkshopRequest {
    workshopRequestDTO: WorkshopRequestDTO;
}

export interface DeleteWorkshopRequest {
    idWorkshop: number;
}

export interface GeneratePdfRequest {
    workshopId: number;
}

export interface GetAllWorkshopsRequest {
    pageable: Pageable;
}

export interface GetWorkshopByIdRequest {
    idWorkshop: number;
}

export interface UpdateClientRequest {
    workshopRequestDTO: WorkshopRequestDTO;
}

/**
 * 
 */
export class WorkshopControllerApi extends runtime.BaseAPI {

    /**
     */
    async createWorkshopRaw(requestParameters: CreateWorkshopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkshopResponseDTO>> {
        if (requestParameters['workshopRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'workshopRequestDTO',
                'Required parameter "workshopRequestDTO" was null or undefined when calling createWorkshop().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/workshops/add`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkshopRequestDTOToJSON(requestParameters['workshopRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkshopResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async createWorkshop(requestParameters: CreateWorkshopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkshopResponseDTO> {
        const response = await this.createWorkshopRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteWorkshopRaw(requestParameters: DeleteWorkshopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['idWorkshop'] == null) {
            throw new runtime.RequiredError(
                'idWorkshop',
                'Required parameter "idWorkshop" was null or undefined when calling deleteWorkshop().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/workshops/{idWorkshop}`.replace(`{${"idWorkshop"}}`, encodeURIComponent(String(requestParameters['idWorkshop']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteWorkshop(requestParameters: DeleteWorkshopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWorkshopRaw(requestParameters, initOverrides);
    }

   

    /**
     */
    async getAllWorkshopsRaw(requestParameters: GetAllWorkshopsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageWorkshopResponseDTO>> {
        if (requestParameters['pageable'] == null) {
            throw new runtime.RequiredError(
                'pageable',
                'Required parameter "pageable" was null or undefined when calling getAllWorkshops().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageable'] != null) {
            queryParameters['pageable'] = requestParameters['pageable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/workshops`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageWorkshopResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getAllWorkshops(requestParameters: GetAllWorkshopsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageWorkshopResponseDTO> {
        const response = await this.getAllWorkshopsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllWorkshops1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WorkshopResponseDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/workshops/showAll`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkshopResponseDTOFromJSON));
    }

    /**
     */
    async getAllWorkshops1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WorkshopResponseDTO>> {
        const response = await this.getAllWorkshops1Raw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getWorkshopByIdRaw(requestParameters: GetWorkshopByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkshopResponseDTO>> {
        if (requestParameters['idWorkshop'] == null) {
            throw new runtime.RequiredError(
                'idWorkshop',
                'Required parameter "idWorkshop" was null or undefined when calling getWorkshopById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/workshops/{idWorkshop}`.replace(`{${"idWorkshop"}}`, encodeURIComponent(String(requestParameters['idWorkshop']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkshopResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getWorkshopById(requestParameters: GetWorkshopByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkshopResponseDTO> {
        const response = await this.getWorkshopByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateClientRaw(requestParameters: UpdateClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkshopResponseDTO>> {
        if (requestParameters['workshopRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'workshopRequestDTO',
                'Required parameter "workshopRequestDTO" was null or undefined when calling updateClient().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/workshops/{id}`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: WorkshopRequestDTOToJSON(requestParameters['workshopRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkshopResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async updateClient(requestParameters: UpdateClientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkshopResponseDTO> {
        const response = await this.updateClientRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
