/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientResponseDTO
 */
export interface ClientResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof ClientResponseDTO
     */
    idClient?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientResponseDTO
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponseDTO
     */
    clientType?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponseDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientResponseDTO
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientResponseDTO
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientResponseDTO
     */
    userFullName?: string;
}

/**
 * Check if a given object implements the ClientResponseDTO interface.
 */
export function instanceOfClientResponseDTO(value: object): value is ClientResponseDTO {
    return true;
}

export function ClientResponseDTOFromJSON(json: any): ClientResponseDTO {
    return ClientResponseDTOFromJSONTyped(json, false);
}

export function ClientResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idClient': json['idClient'] == null ? undefined : json['idClient'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'clientType': json['clientType'] == null ? undefined : json['clientType'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userFullName': json['userFullName'] == null ? undefined : json['userFullName'],
    };
}

export function ClientResponseDTOToJSON(value?: ClientResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idClient': value['idClient'],
        'fullName': value['fullName'],
        'clientType': value['clientType'],
        'email': value['email'],
        'address': value['address'],
        'userId': value['userId'],
        'userFullName': value['userFullName'],
    };
}

