/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientRequestDTO
 */
export interface ClientRequestDTO {
    /**
     * 
     * @type {number}
     * @memberof ClientRequestDTO
     */
    clientId?: number;
    /**
     * 
     * @type {string}
     * @memberof ClientRequestDTO
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRequestDTO
     */
    clientType?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRequestDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRequestDTO
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientRequestDTO
     */
    telephone?: string;
    /**
     * 
     * @type {number}
     * @memberof ClientRequestDTO
     */
    userId?: number;
}

/**
 * Check if a given object implements the ClientRequestDTO interface.
 */
export function instanceOfClientRequestDTO(value: object): value is ClientRequestDTO {
    return true;
}

export function ClientRequestDTOFromJSON(json: any): ClientRequestDTO {
    return ClientRequestDTOFromJSONTyped(json, false);
}

export function ClientRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'clientType': json['clientType'] == null ? undefined : json['clientType'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'telephone': json['telephone'] == null ? undefined : json['telephone'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ClientRequestDTOToJSON(value?: ClientRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'clientId': value['clientId'],
        'fullName': value['fullName'],
        'clientType': value['clientType'],
        'email': value['email'],
        'address': value['address'],
        'telephone': value['telephone'],
        'telephone': value['telephone'],
        'userId': value['userId'],
    };
}

