/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FamilleProduct
 */
export interface FamilleProduct {
    /**
     * 
     * @type {number}
     * @memberof FamilleProduct
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FamilleProduct
     */
    designation?: string;
}

/**
 * Check if a given object implements the FamilleProduct interface.
 */
export function instanceOfFamilleProduct(value: object): value is FamilleProduct {
    return true;
}

export function FamilleProductFromJSON(json: any): FamilleProduct {
    return FamilleProductFromJSONTyped(json, false);
}

export function FamilleProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilleProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'designation': json['designation'] == null ? undefined : json['designation'],
    };
}

export function FamilleProductToJSON(value?: FamilleProduct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'designation': value['designation'],
    };
}

