/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileStorage
 */
export interface FileStorage {
    /**
     * 
     * @type {number}
     * @memberof FileStorage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FileStorage
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof FileStorage
     */
    fileType?: string;
    /**
     * 
     * @type {number}
     * @memberof FileStorage
     */
    fileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof FileStorage
     */
    data?: string;
    /**
     * 
     * @type {Date}
     * @memberof FileStorage
     */
    creationDate?: Date;
}

/**
 * Check if a given object implements the FileStorage interface.
 */
export function instanceOfFileStorage(value: object): value is FileStorage {
    return true;
}

export function FileStorageFromJSON(json: any): FileStorage {
    return FileStorageFromJSONTyped(json, false);
}

export function FileStorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileStorage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'fileType': json['fileType'] == null ? undefined : json['fileType'],
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
        'data': json['data'] == null ? undefined : json['data'],
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
    };
}

export function FileStorageToJSON(value?: FileStorage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'fileName': value['fileName'],
        'fileType': value['fileType'],
        'fileSize': value['fileSize'],
        'data': value['data'],
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
    };
}

