/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtResponse
 */
export interface JwtResponse {
    /**
     * 
     * @type {string}
     * @memberof JwtResponse
     */
    jwtToken?: string;
    /**
     * 
     * @type {string}
     * @memberof JwtResponse
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof JwtResponse
     */
    role?: string;
}

/**
 * Check if a given object implements the JwtResponse interface.
 */
export function instanceOfJwtResponse(value: object): value is JwtResponse {
    return true;
}

export function JwtResponseFromJSON(json: any): JwtResponse {
    return JwtResponseFromJSONTyped(json, false);
}

export function JwtResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jwtToken': json['jwtToken'] == null ? undefined : json['jwtToken'],
        'username': json['username'] == null ? undefined : json['username'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function JwtResponseToJSON(value?: JwtResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jwtToken': value['jwtToken'],
        'username': value['username'],
        'role': value['role'],
    };
}

