/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JwtRequest
 */
export interface JwtRequest {
    /**
     * 
     * @type {string}
     * @memberof JwtRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof JwtRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the JwtRequest interface.
 */
export function instanceOfJwtRequest(value: object): value is JwtRequest {
    return true;
}

export function JwtRequestFromJSON(json: any): JwtRequest {
    return JwtRequestFromJSONTyped(json, false);
}

export function JwtRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JwtRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function JwtRequestToJSON(value?: JwtRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

