/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderResponseDTO
 */
export interface OrderResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof OrderResponseDTO
     */
    idOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderResponseDTO
     */
    clientName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderResponseDTO
     */
    productName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderResponseDTO
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderResponseDTO
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderResponseDTO interface.
 */
export function instanceOfOrderResponseDTO(value: object): value is OrderResponseDTO {
    return true;
}

export function OrderResponseDTOFromJSON(json: any): OrderResponseDTO {
    return OrderResponseDTOFromJSONTyped(json, false);
}

export function OrderResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idOrder': json['idOrder'] == null ? undefined : json['idOrder'],
        'clientName': json['clientName'] == null ? undefined : json['clientName'],
        'productName': json['productName'] == null ? undefined : json['productName'],
        'date': json['date'] == null ? undefined : json['date'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function OrderResponseDTOToJSON(value?: OrderResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idOrder': value['idOrder'],
        'clientName': value['clientName'],
        'productName': value['productName'],
        'date': value['date'],
        'quantity': value['quantity'],
    };
}

