/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderRequestDTO
 */
export interface OrderRequestDTO {
    /**
     * 
     * @type {number}
     * @memberof OrderRequestDTO
     */
    clientId?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderRequestDTO
     */
    productId?: number;
    /**
     * 
     * @type {Date}
     * @memberof OrderRequestDTO
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrderRequestDTO
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderRequestDTO interface.
 */
export function instanceOfOrderRequestDTO(value: object): value is OrderRequestDTO {
    return true;
}

export function OrderRequestDTOFromJSON(json: any): OrderRequestDTO {
    return OrderRequestDTOFromJSONTyped(json, false);
}

export function OrderRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function OrderRequestDTOToJSON(value?: OrderRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'clientId': value['clientId'],
        'productId': value['productId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'quantity': value['quantity'],
    };
}

