/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderResponseDTO
 */
export interface OrderResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof OrderResponseDTO
     */
    idOrder?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderResponseDTO
     */
    clientId?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderResponseDTO
     */
    productId?: number;
    /**
     * 
     * @type {Date}
     * @memberof OrderResponseDTO
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrderResponseDTO
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderResponseDTO interface.
 */
export function instanceOfOrderResponseDTO(value: object): value is OrderResponseDTO {
    return true;
}

export function OrderResponseDTOFromJSON(json: any): OrderResponseDTO {
    return OrderResponseDTOFromJSONTyped(json, false);
}

export function OrderResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idOrder': json['idOrder'] == null ? undefined : json['idOrder'],
        'clientId': json['clientId'] == null ? undefined : json['clientId'],
        'productId': json['productId'] == null ? undefined : json['productId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function OrderResponseDTOToJSON(value?: OrderResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idOrder': value['idOrder'],
        'clientId': value['clientId'],
        'productId': value['productId'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'quantity': value['quantity'],
    };
}

