/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';
import type { ProductResponse } from './ProductResponse';
import {
    ProductResponseFromJSON,
    ProductResponseFromJSONTyped,
    ProductResponseToJSON,
} from './ProductResponse';

/**
 * 
 * @export
 * @interface PageProductResponse
 */
export interface PageProductResponse {
    /**
     * 
     * @type {number}
     * @memberof PageProductResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageProductResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageProductResponse
     */
    size?: number;
    /**
     * 
     * @type {Array<ProductResponse>}
     * @memberof PageProductResponse
     */
    content?: Array<ProductResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageProductResponse
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PageProductResponse
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {boolean}
     * @memberof PageProductResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageProductResponse
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageProductResponse
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageProductResponse
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageProductResponse
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageProductResponse interface.
 */
export function instanceOfPageProductResponse(value: object): value is PageProductResponse {
    return true;
}

export function PageProductResponseFromJSON(json: any): PageProductResponse {
    return PageProductResponseFromJSONTyped(json, false);
}

export function PageProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ProductResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': Array.isArray(json['sort']) ? json['sort'].map(SortObjectFromJSON) : [SortObjectFromJSON(json['sort'])],         
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageProductResponseToJSON(value?: PageProductResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ProductResponseToJSON)),
        'number': value['number'],

        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortObjectToJSON)),
     'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

