/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { RawMaterialResponseDTO } from './RawMaterialResponseDTO';
import {
    RawMaterialResponseDTOFromJSON,
    RawMaterialResponseDTOFromJSONTyped,
    RawMaterialResponseDTOToJSON,
} from './RawMaterialResponseDTO';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageRawMaterialResponseDTO
 */
export interface PageRawMaterialResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof PageRawMaterialResponseDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRawMaterialResponseDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRawMaterialResponseDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<RawMaterialResponseDTO>}
     * @memberof PageRawMaterialResponseDTO
     */
    content?: Array<RawMaterialResponseDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageRawMaterialResponseDTO
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PageRawMaterialResponseDTO
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {number}
     * @memberof PageRawMaterialResponseDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageRawMaterialResponseDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageRawMaterialResponseDTO
     */
    last?: boolean;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageRawMaterialResponseDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageRawMaterialResponseDTO
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageRawMaterialResponseDTO interface.
 */
export function instanceOfPageRawMaterialResponseDTO(value: object): value is PageRawMaterialResponseDTO {
    return true;
}

export function PageRawMaterialResponseDTOFromJSON(json: any): PageRawMaterialResponseDTO {
    return PageRawMaterialResponseDTOFromJSONTyped(json, false);
}

export function PageRawMaterialResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageRawMaterialResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(RawMaterialResponseDTOFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
'sort': Array.isArray(json['sort']) 
            ? json['sort'].map(SortObjectFromJSON) 
            : json['sort'] != null && typeof json['sort'] === 'object'
                ? [SortObjectFromJSON(json['sort'])] // Wrap the object in an array
                : [],        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageRawMaterialResponseDTOToJSON(value?: PageRawMaterialResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(RawMaterialResponseDTOToJSON)),
        'number': value['number'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortObjectToJSON)),
        'numberOfElements': value['numberOfElements'],
        'first': value['first'],
        'last': value['last'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

