/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
} from './PageableObject';
import type { ClientResponseDTO } from './ClientResponseDTO';
import {
    ClientResponseDTOFromJSON,
    ClientResponseDTOFromJSONTyped,
    ClientResponseDTOToJSON,
} from './ClientResponseDTO';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageClientResponseDTO
 */
export interface PageClientResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof PageClientResponseDTO
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageClientResponseDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageClientResponseDTO
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageClientResponseDTO
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageClientResponseDTO
     */
    size?: number;
    /**
     * 
     * @type {Array<ClientResponseDTO>}
     * @memberof PageClientResponseDTO
     */
    content?: Array<ClientResponseDTO>;
    /**
     * 
     * @type {number}
     * @memberof PageClientResponseDTO
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PageClientResponseDTO
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {number}
     * @memberof PageClientResponseDTO
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageClientResponseDTO
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageClientResponseDTO
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageClientResponseDTO interface.
 */
export function instanceOfPageClientResponseDTO(value: object): value is PageClientResponseDTO {
    return true;
}

export function PageClientResponseDTOFromJSON(json: any): PageClientResponseDTO {
    return PageClientResponseDTOFromJSONTyped(json, false);
}

export function PageClientResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageClientResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ClientResponseDTOFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortObjectFromJSON)),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageClientResponseDTOToJSON(value?: PageClientResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'first': value['first'],
        'last': value['last'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ClientResponseDTOToJSON)),
        'number': value['number'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortObjectToJSON)),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

