/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    designation?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    dimension?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    productionDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    productionCost?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    logoName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    logoType?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    subCategory?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    rawMaterial?: string;
}

/**
 * Check if a given object implements the ProductResponse interface.
 */
export function instanceOfProductResponse(value: object): value is ProductResponse {
    return true;
}

export function ProductResponseFromJSON(json: any): ProductResponse {
    return ProductResponseFromJSONTyped(json, false);
}

export function ProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'designation': json['designation'] == null ? undefined : json['designation'],
        'color': json['color'] == null ? undefined : json['color'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'dimension': json['dimension'] == null ? undefined : json['dimension'],
        'productionDuration': json['productionDuration'] == null ? undefined : json['productionDuration'],
        'price': json['price'] == null ? undefined : json['price'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'productionCost': json['productionCost'] == null ? undefined : json['productionCost'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'logoName': json['logoName'] == null ? undefined : json['logoName'],
        'logoType': json['logoType'] == null ? undefined : json['logoType'],
        'subCategory': json['subCategory'] == null ? undefined : json['subCategory'],
        'rawMaterial': json['rawMaterial'] == null ? undefined : json['rawMaterial'],
    };
}

export function ProductResponseToJSON(value?: ProductResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'reference': value['reference'],
        'designation': value['designation'],
        'color': value['color'],
        'weight': value['weight'],
        'dimension': value['dimension'],
        'productionDuration': value['productionDuration'],
        'price': value['price'],
        'quantity': value['quantity'],
        'productionCost': value['productionCost'],
        'logo': value['logo'],
        'logoName': value['logoName'],
        'logoType': value['logoType'],
        'subCategory': value['subCategory'],
        'rawMaterial': value['rawMaterial'],
    };
}

