/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductRequest
 */
export interface ProductRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductRequest
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequest
     */
    designation?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductRequest
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    weight?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    dimension?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    productionDuration?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    productionCost?: number;
    /**
     * 
     * @type {Blob}
     * @memberof ProductRequest
     */
    logo?: Blob;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    subCategory?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductRequest
     */
    rawMaterial?: number;
}

/**
 * Check if a given object implements the ProductRequest interface.
 */
export function instanceOfProductRequest(value: object): value is ProductRequest {
    return true;
}

export function ProductRequestFromJSON(json: any): ProductRequest {
    return ProductRequestFromJSONTyped(json, false);
}

export function ProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'designation': json['designation'] == null ? undefined : json['designation'],
        'color': json['color'] == null ? undefined : json['color'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'dimension': json['dimension'] == null ? undefined : json['dimension'],
        'productionDuration': json['productionDuration'] == null ? undefined : json['productionDuration'],
        'price': json['price'] == null ? undefined : json['price'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'productionCost': json['productionCost'] == null ? undefined : json['productionCost'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'subCategory': json['subCategory'] == null ? undefined : json['subCategory'],
        'rawMaterial': json['rawMaterial'] == null ? undefined : json['rawMaterial'],
    };
}

export function ProductRequestToJSON(value?: ProductRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'reference': value['reference'],
        'designation': value['designation'],
        'color': value['color'],
        'weight': value['weight'],
        'dimension': value['dimension'],
        'productionDuration': value['productionDuration'],
        'price': value['price'],
        'quantity': value['quantity'],
        'productionCost': value['productionCost'],
        'logo': value['logo'],
        'subCategory': value['subCategory'],
        'rawMaterial': value['rawMaterial'],
    };
}

