/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RawMaterialResponseDTO
 */
export interface RawMaterialResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof RawMaterialResponseDTO
     */
    idMaterial?: number;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialResponseDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialResponseDTO
     */
    materialType?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialResponseDTO
     */
    supplier?: string;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialResponseDTO
     */
    availableQuantity?: number;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialResponseDTO
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialResponseDTO
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof RawMaterialResponseDTO
     */
    origin?: string;
    /**
     * 
     * @type {number}
     * @memberof RawMaterialResponseDTO
     */
    unitPrice?: number;
}

/**
 * Check if a given object implements the RawMaterialResponseDTO interface.
 */
export function instanceOfRawMaterialResponseDTO(value: object): value is RawMaterialResponseDTO {
    return true;
}

export function RawMaterialResponseDTOFromJSON(json: any): RawMaterialResponseDTO {
    return RawMaterialResponseDTOFromJSONTyped(json, false);
}

export function RawMaterialResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RawMaterialResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idMaterial': json['idMaterial'] == null ? undefined : json['idMaterial'],
        'name': json['name'] == null ? undefined : json['name'],
        'materialType': json['materialType'] == null ? undefined : json['materialType'],
        'supplier': json['supplier'] == null ? undefined : json['supplier'],
        'availableQuantity': json['availableQuantity'] == null ? undefined : json['availableQuantity'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'color': json['color'] == null ? undefined : json['color'],
        'origin': json['origin'] == null ? undefined : json['origin'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
    };
}

export function RawMaterialResponseDTOToJSON(value?: RawMaterialResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idMaterial': value['idMaterial'],
        'name': value['name'],
        'materialType': value['materialType'],
        'supplier': value['supplier'],
        'availableQuantity': value['availableQuantity'],
        'unit': value['unit'],
        'color': value['color'],
        'origin': value['origin'],
        'unitPrice': value['unitPrice'],
    };
}

