/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubCategoryResponseDTO
 */
export interface SubCategoryResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof SubCategoryResponseDTO
     */
    idSubCategory?: number;
    /**
     * 
     * @type {string}
     * @memberof SubCategoryResponseDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SubCategoryResponseDTO
     */
    reference?: string;
}

/**
 * Check if a given object implements the SubCategoryResponseDTO interface.
 */
export function instanceOfSubCategoryResponseDTO(value: object): value is SubCategoryResponseDTO {
    return true;
}

export function SubCategoryResponseDTOFromJSON(json: any): SubCategoryResponseDTO {
    return SubCategoryResponseDTOFromJSONTyped(json, false);
}

export function SubCategoryResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubCategoryResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idSubCategory': json['idSubCategory'] == null ? undefined : json['idSubCategory'],
        'name': json['name'] == null ? undefined : json['name'],
        'reference': json['reference'] == null ? undefined : json['reference'],
    };
}

export function SubCategoryResponseDTOToJSON(value?: SubCategoryResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idSubCategory': value['idSubCategory'],
        'name': value['name'],
        'reference': value['reference'],
    };
}

