/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponseDTO
 */
export interface UserResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof UserResponseDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof UserResponseDTO
     */
    phoneNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserResponseDTO
     */
    lastAccess?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponseDTO
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    logoName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    logoType?: string;
}

/**
 * Check if a given object implements the UserResponseDTO interface.
 */
export function instanceOfUserResponseDTO(value: object): value is UserResponseDTO {
    return true;
}

export function UserResponseDTOFromJSON(json: any): UserResponseDTO {
    return UserResponseDTOFromJSONTyped(json, false);
}

export function UserResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'role': json['role'] == null ? undefined : json['role'],
        'status': json['status'] == null ? undefined : json['status'],
        'lastAccess': json['lastAccess'] == null ? undefined : (new Date(json['lastAccess'])),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'logoName': json['logoName'] == null ? undefined : json['logoName'],
        'logoType': json['logoType'] == null ? undefined : json['logoType'],
    };
}

export function UserResponseDTOToJSON(value?: UserResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'address': value['address'],
        'phoneNumber': value['phoneNumber'],
        'role': value['role'],
        'status': value['status'],
        'lastAccess': value['lastAccess'] == null ? undefined : ((value['lastAccess']).toISOString()),
        'enabled': value['enabled'],
        'logo': value['logo'],
        'logoName': value['logoName'],
        'logoType': value['logoType'],
    };
}

