/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkshopRequestDTO
 */
export interface WorkshopRequestDTO {
    /**
     * 
     * @type {number}
     * @memberof WorkshopRequestDTO
     */
    idWorkshop?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkshopRequestDTO
     */
    workshopNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkshopRequestDTO
     */
    productionCapacity?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkshopRequestDTO
     */
    machineCount?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkshopRequestDTO
     */
    machineCost?: number;
}

/**
 * Check if a given object implements the WorkshopRequestDTO interface.
 */
export function instanceOfWorkshopRequestDTO(value: object): value is WorkshopRequestDTO {
    return true;
}

export function WorkshopRequestDTOFromJSON(json: any): WorkshopRequestDTO {
    return WorkshopRequestDTOFromJSONTyped(json, false);
}

export function WorkshopRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkshopRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idWorkshop': json['idWorkshop'] == null ? undefined : json['idWorkshop'],
        'workshopNumber': json['workshopNumber'] == null ? undefined : json['workshopNumber'],
        'productionCapacity': json['productionCapacity'] == null ? undefined : json['productionCapacity'],
        'machineCount': json['machineCount'] == null ? undefined : json['machineCount'],
        'machineCost': json['machineCost'] == null ? undefined : json['machineCost'],
    };
}

export function WorkshopRequestDTOToJSON(value?: WorkshopRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idWorkshop': value['idWorkshop'],
        'workshopNumber': value['workshopNumber'],
        'productionCapacity': value['productionCapacity'],
        'machineCount': value['machineCount'],
        'machineCost': value['machineCost'],
    };
}

